### ISSUE TITLE
Question for a blog post

### ISSUE THREAD

**Issue by maelle** [sebpardo/myebird#4]
:wave: @sebpardo ! I'm working on a blog post about `rebird` & `auk` for rOpenSci's blog. I'll briefly mention this WIP package as well... unless you tell me not to!

**Comment by sebpardo** [comment]
Hi @maelle! Please mention this package if you think it's relevant.

Perhaps it's outside of the scope of your article, but this Shiny app might also be of interest:

http://www.ebirdedgeapp.io/

After uploading your personal eBird data, it shows evolutionary distinctiveness and globally endangered (EDGE) scores for the species in the list. 

Please let me know when the blog post is out!

**Comment by maelle** [comment]
I actually saw it right after I wrote that and added a sentence about the app, very cool! Thanks for answering and yes I'll ping you when it's out (in the next two months!).
