### ISSUE TITLE
Warning for `tbl_df()` being deprecated in dplyr 1.0.0

### ISSUE THREAD

**Issue by VLucet** [sebpardo/myebird#5]
Hi, love the idea for the package! 
Just spotted a simple warning:
```r
> my_data <- ebirdclean("MyEBirdData.csv")
Warning message:
`tbl_df()` was deprecated in dplyr 1.0.0.
Please use `tibble::as_tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```
I can do a simple PR for this!

**Comment by sebpardo** [comment]
Hi @VLucet, thank you for doing this! I haven't touched this repository in over 5 years so I'm not sure how things are working with it. If you play around with it please keep me posted as I'm curious to know what works and what doesn't.
